name: Blogger Auto Bot

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour at minute 0
  workflow_dispatch:  # Allow manual triggering

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p config
          mkdir -p logs
          mkdir -p images

      - name: Create credentials file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' | jq '.' > config/credentials.json

      - name: Create token file directly
        run: |
          echo '${{ secrets.BLOGGER_TOKEN }}' | jq '.' > config/token.json

      - name: Create .env file
        run: |
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" > .env
          echo "BLOGGER_ID=${{ secrets.BLOGGER_ID }}" >> .env
          # Only add Pixabay API key if it exists in secrets
          if [ -n "$PIXABAY_API_KEY" ]; then
            echo "PIXABAY_API_KEY=$PIXABAY_API_KEY" >> .env
          fi
        env:
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY || '' }}

      - name: Run blogger bot
        run: python main.py
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          BLOGGER_ID: ${{ secrets.BLOGGER_ID }}
