name: Blogger Auto Bot

on:
  schedule:
    - cron: "0 */1 * * *" # Run every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create config directory
        run: mkdir -p config

      - name: Create credentials file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > config/credentials.json

      - name: Create token file directly
        run: |
          echo '${{ secrets.BLOGGER_TOKEN }}' > config/token.json

      - name: Create .env file
        run: |
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" > .env
          echo "BLOGGER_ID=${{ secrets.BLOGGER_ID }}" >> .env

      - name: Run blogger bot
        run: python main.py
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          BLOGGER_ID: ${{ secrets.BLOGGER_ID }}
